### PR TITLE
feat: updating and correcting bugs

### PR DESCRIPTION
**Pull request by alanSxSx**
Adicionando mais shelters de testes. Corrigindo 3 linhas que tem um "(e" errado.

### CODE REVIEW

**Comment by alanSxSx** [comment]
image

**Comment by alanSxSx** [comment]
#156

**Comment by giggio** [comment]
@alanSxSx Tem mais de 2 mil linhas novas, é isso mesmo?

**Comment by alanSxSx** [comment]
As adições das linhas se deve pela formatação do código.

image

Na nova formatação, facilita a visualização e organização.

image

**Comment by alanSxSx** [comment]
As adições dos Shelters foram da linha 247 até 314.

INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213001', '606a9ed3-b5f7-4d63-8da9-c65adf0a927a', 100, '2024-05-09T16:20:28.294Z', null);
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213001', '5cac0471-262c-4408-8fd7-00e99f5a9869', 10, '2024-05-09T16:20:35.057Z', null);
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213001', '04156fe1-e392-4283-a919-1e25908dbec1', 1, '2024-05-09T16:20:48.077Z', null);
INSERT INTO public.shelters
	(id, pix, address, pet_friendly, sheltered_people, capacity, contact, created_at, updated_at, name, priority_sum, latitude, longitude, verified, city)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213001', null, 'Rua Coronel Corte Real, 975 - Petrópolis, Porto Alegre', null, null, null, null, '2024-05-07T01:04:29.240Z', '2024-05-09T16:20:48.068Z', 'Simers2', 861, null, null, true, 'Porto Alegre');
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213002', '606a9ed3-b5f7-4d63-8da9-c65adf0a927a', 100, '2024-05-09T16:20:28.294Z', null);
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213002', '5cac0471-262c-4408-8fd7-00e99f5a9869', 10, '2024-05-09T16:20:35.057Z', null);
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213002', '04156fe1-e392-4283-a919-1e25908dbec1', 1, '2024-05-09T16:20:48.077Z', null);
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213002', '62bd5d05-ba37-497a-a1a1-56795813790d', 100, '2024-05-09T16:20:48.077Z', null);
INSERT INTO public.shelters
	(id, pix, address, pet_friendly, sheltered_people, capacity, contact, created_at, updated_at, name, priority_sum, latitude, longitude, verified, city)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213002', null, 'Rua Coronel Corte Real, 975 - Petrópolis, Porto Alegre', null, null, null, null, '2024-05-07T01:04:29.240Z', '2024-05-09T16:20:48.068Z', 'Teste1', 861, null, null, true, 'Lajeado');
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213003', '1fde16af-ef8a-4686-b021-cafc1c5179cf', 100, '2024-05-09T16:20:28.294Z', null);
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213003', '5cac0471-262c-4408-8fd7-00e99f5a9869', 10, '2024-05-09T16:20:35.057Z', null);
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213003', 'ddd006a5-eac6-44de-ad77-b9386f25ef9c', 1, '2024-05-09T16:20:48.077Z', null);
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213003', '8fe8f879-5cc8-4670-a13d-9d2d6bb24017', 100, '2024-05-09T16:20:48.077Z', null);
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213003', '38f2c85a-d46f-4cd4-92a6-70cd8b55851a', 100, '2024-05-09T16:20:48.077Z', null);
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213003', 'ceebd729-eecc-420e-8e90-f764a487b202', 100, '2024-05-09T16:20:48.077Z', null);
INSERT INTO public.shelter_supplies
	(shelter_id, supply_id, priority, created_at, updated_at)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213003', '2b72c607-f5b6-4907-88e9-1a2d50045b18', 100, '2024-05-09T16:20:48.077Z', null);
INSERT INTO public.shelters
	(id, pix, address, pet_friendly, sheltered_people, capacity, contact, created_at, updated_at, name, priority_sum, latitude, longitude, verified, city)
VALUES
	('7f21ccc7-d1de-4a23-b710-260761213003', null, 'Rua Coronel Corte Real, 975 - Petrópolis, Porto Alegre', null, null, null, null, '2024-05-07T01:04:29.240Z', '2024-05-09T16:20:48.068Z', 'Teste2', 861, null, null, true, 'Guaíba');

**Comment by alanSxSx** [comment]
Irei fechar esse PR, pois um arquivo novo do DUMP foi passado. Irei adicionar um novo PR

**Pull request closed without merging**
